/**
 * Build a versioned handoff pack per project.
 *
 * Output layout (per project):
 *
 *   Projects/<id>/artifacts/handoff/v<version>/
 *     manifest.json     — machine-readable snapshot (every metadata surface)
 *     README.md         — human-readable handoff doc (TOC, screenshots, embeds)
 *     brief.md          — single-file concatenation of brief/*.md
 *     data/             — copy of every fixture JSON
 *     docs/             — selected authored markdown (sitemap, journeys, permissions)
 *     snapshots/        — Playwright PNGs (only when --with-snapshots was used
 *                         and the snapshot script wrote into the source dir)
 *
 * Usage:
 *
 *   npm run handoff                          # all projects
 *   npm run handoff -- --project <id>        # one project
 *   npm run handoff -- --skip-validation     # dangerous; for emergency cuts
 *
 * Snapshots are NOT generated by this script — run `npm run snapshot --
 * --project <id>` separately (it needs `npm run dev` running). Any PNGs
 * already present under `Projects/<id>/artifacts/snapshots/` are copied
 * into the handoff folder.
 */

import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { discoverProjects, type DiscoveredProject } from './lib/discover-projects';
import { validateRegistry, type ValidationIssue } from '../src/mockup-os/framework/validation';
import { parseSitemap } from '../src/mockup-os/framework/sitemap-parser';
import type { Permission, Section } from '../src/mockup-os/framework/types';

interface CliArgs {
  project?: string;
  skipValidation: boolean;
}

export interface BuildHandoffOptions {
  /** Skip validation errors. False by default — only flip in emergency. */
  skipValidation?: boolean;
  /** Receive each log line. Defaults to console.log. */
  log?: (msg: string) => void;
}

export interface BuildHandoffResult {
  projectId: string;
  outDir: string;
  manifestPath: string;
  snapshots: number;
  warnings: number;
}

function parseArgs(argv: string[]): CliArgs {
  const out: CliArgs = { skipValidation: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--project' && argv[i + 1]) {
      out.project = argv[++i];
    } else if (a === '--skip-validation') {
      out.skipValidation = true;
    }
  }
  return out;
}

const stamp = new Date().toISOString();

interface BuildContext {
  project: DiscoveredProject;
  outDir: string;
  warnings: ReadonlyArray<ValidationIssue>;
  brief: { combined: string; files: { name: string; content: string }[]; exists: boolean };
  sitemapEntries: ReturnType<typeof parseSitemap> | null;
  snapshotFiles: string[];
  dataFiles: string[];
}

/**
 * Build a handoff pack for one project. Importable from the sidecar so
 * `/api/projects/:id/handoff` can stream progress without spawning a
 * subprocess (avoids Windows shell-quoting issues on paths with spaces).
 *
 * Throws on validation errors unless `skipValidation` is true.
 */
export function buildHandoff(
  project: DiscoveredProject,
  options: BuildHandoffOptions = {},
): BuildHandoffResult {
  const log = options.log ?? ((msg: string) => console.log(msg));
  const { meta, screens, journeys, fixtures, config } = project;
  const report = validateRegistry({ screens, journeys, fixtures, config });

  if (!report.ok && !options.skipValidation) {
    const codes = report.errors.map((e) => `${e.code}${e.subject ? ` [${e.subject}]` : ''}`).join(', ');
    throw new Error(
      `Registry has ${report.errors.length} error(s) for ${meta.id}: ${codes}. Fix or pass skipValidation: true.`,
    );
  }

  const outDir = join(project.rootPath, 'artifacts', 'handoff', `v${meta.version}`);
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  log(`Wiped and recreated ${outDir}`);

  const ctx: BuildContext = {
    project,
    outDir,
    warnings: report.warnings,
    brief: collectBrief(project),
    sitemapEntries: collectSitemap(project),
    snapshotFiles: copySnapshots(project, outDir),
    dataFiles: copyData(project, outDir),
  };

  copyDocs(project, outDir);
  log(`Copied ${ctx.dataFiles.length} data file(s), ${ctx.snapshotFiles.length} snapshot(s)`);
  writeBrief(ctx);
  if (ctx.brief.exists) log(`Wrote brief.md (${ctx.brief.files.length} sections combined)`);
  writeManifest(ctx);
  log('Wrote manifest.json');
  writeReadme(ctx);
  log('Wrote README.md');

  const summary =
    `✔ ${meta.id} v${meta.version} → ${outDir}` +
    (ctx.snapshotFiles.length === 0 ? ' (no snapshots)' : ` · ${ctx.snapshotFiles.length} screenshots`);
  log(summary);

  return {
    projectId: meta.id,
    outDir,
    manifestPath: join(outDir, 'manifest.json'),
    snapshots: ctx.snapshotFiles.length,
    warnings: report.warnings.length,
  };
}

function buildProject(project: DiscoveredProject, args: CliArgs): void {
  // CLI wrapper: hard-fail on validation errors unless --skip-validation,
  // matching pre-Phase-11 behaviour. Sidecar prefers `buildHandoff` directly.
  try {
    buildHandoff(project, { skipValidation: args.skipValidation });
  } catch (err) {
    console.error((err as Error).message);
    process.exit(1);
  }
}

// ─── data copy ──────────────────────────────────────────────────────

function copyData(project: DiscoveredProject, outDir: string): string[] {
  const src = join(project.rootPath, 'data');
  const dst = join(outDir, 'data');
  if (!existsSync(src) || !statSync(src).isDirectory()) return [];
  mkdirSync(dst, { recursive: true });
  const files: string[] = [];
  for (const name of readdirSync(src)) {
    if (!name.toLowerCase().endsWith('.json')) continue;
    const full = join(src, name);
    if (!statSync(full).isFile()) continue;
    copyFileSync(full, join(dst, name));
    files.push(name);
  }
  return files.sort();
}

// ─── docs copy (selected, not full tree) ────────────────────────────

function copyDocs(project: DiscoveredProject, outDir: string): void {
  const src = join(project.rootPath, 'docs');
  if (!existsSync(src)) return;
  const dst = join(outDir, 'docs');
  mkdirSync(dst, { recursive: true });
  // Copy these subtrees / files if they exist. Anything else stays out
  // of the handoff pack to keep it focused.
  const include = ['sitemap.md', 'journeys', 'permissions', 'features', 'styles', 'components', 'layouts'];
  for (const entry of include) {
    const from = join(src, entry);
    if (!existsSync(from)) continue;
    cpSync(from, join(dst, entry), { recursive: true });
  }
}

// ─── snapshots copy ─────────────────────────────────────────────────

function copySnapshots(project: DiscoveredProject, outDir: string): string[] {
  const src = join(project.rootPath, 'artifacts', 'snapshots');
  if (!existsSync(src) || !statSync(src).isDirectory()) return [];
  const dst = join(outDir, 'snapshots');
  mkdirSync(dst, { recursive: true });
  const files: string[] = [];
  for (const name of readdirSync(src)) {
    if (!name.toLowerCase().endsWith('.png')) continue;
    const full = join(src, name);
    if (!statSync(full).isFile()) continue;
    copyFileSync(full, join(dst, name));
    files.push(name);
  }
  return files.sort();
}

// ─── brief snapshot ─────────────────────────────────────────────────

function collectBrief(project: DiscoveredProject) {
  const briefDir = join(project.rootPath, 'brief');
  if (!existsSync(briefDir) || !statSync(briefDir).isDirectory()) {
    return { combined: '', files: [], exists: false };
  }
  const files = readdirSync(briefDir)
    .filter((n) => n.toLowerCase().endsWith('.md'))
    .sort()
    .map((name) => ({
      name,
      content: readFileSync(join(briefDir, name), 'utf8'),
    }));
  const combined = files
    .map((f) => `<!-- file: ${f.name} -->\n${f.content.trim()}\n`)
    .join('\n---\n\n');
  return { combined, files, exists: files.length > 0 };
}

function writeBrief(ctx: BuildContext) {
  if (!ctx.brief.exists) return;
  writeFileSync(join(ctx.outDir, 'brief.md'), ctx.brief.combined, 'utf8');
}

// ─── sitemap ────────────────────────────────────────────────────────

function collectSitemap(project: DiscoveredProject) {
  const file = join(project.rootPath, 'docs', 'sitemap.md');
  if (!existsSync(file)) return null;
  return parseSitemap(readFileSync(file, 'utf8'));
}

// ─── manifest ───────────────────────────────────────────────────────

function writeManifest(ctx: BuildContext) {
  const { project, warnings, sitemapEntries, snapshotFiles, dataFiles } = ctx;
  const { meta, screens, journeys, fixtures, config } = project;

  const permissions: Permission[] = [...(config.permissions ?? [])];
  const sections: Section[] = [...(config.sections ?? [])];

  const manifest = {
    project: {
      id: meta.id,
      name: meta.name,
      description: meta.description,
      version: meta.version,
    },
    generatedAt: stamp,
    summary: {
      screens: screens.length,
      journeys: journeys.length,
      fixtures: fixtures.length,
      permissions: permissions.length,
      sections: sections.length,
      ghosts: sitemapEntries
        ? sitemapEntries.entries.filter((e) => e.kind === 'ghost').length
        : 0,
      snapshots: snapshotFiles.length,
      warnings: warnings.length,
    },
    screens: screens.map((s) => ({
      id: s.id,
      title: s.title,
      route: s.route,
      status: s.status,
      version: s.version,
      layoutFamily: s.layoutFamily,
      viewport: s.viewport,
      description: s.description,
      journeys: s.journeys,
      relatedScreens: s.relatedScreens,
      states: s.states.map(({ id, label, description }) => ({ id, label, description })),
      defaultStateId: s.defaultStateId,
      fixtures: s.fixtures,
      permissions: s.permissions ?? [],
      sections: s.sections ?? [],
      knownGaps: s.knownGaps,
      components: s.components,
    })),
    journeys: journeys.map((j) => ({
      id: j.id,
      title: j.title,
      description: j.description,
      steps: j.steps,
      group: j.group,
      source: j.source,
    })),
    fixtures: fixtures.map((f) => ({
      id: f.id,
      screenId: f.screenId,
      description: f.description,
      bundledAs: dataFiles.find((n) => n === `${f.id}.json`),
    })),
    permissions,
    sections,
    sitemap: sitemapEntries
      ? sitemapEntries.entries.map((e) => ({
          route: e.route,
          title: e.title,
          kind: e.kind,
          screenId: e.screenId,
          rationale: e.rationale,
          sectionId: e.sectionId,
        }))
      : null,
    snapshots: snapshotFiles,
    warnings,
  };

  writeFileSync(join(ctx.outDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
}

// ─── README (human-facing) ──────────────────────────────────────────

function writeReadme(ctx: BuildContext) {
  const { project, warnings, sitemapEntries, snapshotFiles, brief } = ctx;
  const { meta, screens, journeys, fixtures, config } = project;
  const permissions: Permission[] = [...(config.permissions ?? [])];
  const sections: Section[] = [...(config.sections ?? [])];

  const ghostCount = sitemapEntries
    ? sitemapEntries.entries.filter((e) => e.kind === 'ghost').length
    : 0;

  const lines: string[] = [];

  lines.push(`# ${meta.name} — Handoff v${meta.version}`);
  lines.push('');
  lines.push(`> ${meta.description}`);
  lines.push('');
  lines.push(`Generated: \`${stamp}\``);
  lines.push('');

  // ── TL;DR
  lines.push('## At a glance');
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push(`| Screens | ${screens.length} |`);
  lines.push(`| Journeys | ${journeys.length} |`);
  lines.push(`| Fixtures | ${fixtures.length} |`);
  lines.push(`| Permissions | ${permissions.length} |`);
  lines.push(`| Sections | ${sections.length} |`);
  if (ghostCount > 0) lines.push(`| Proposed (ghost) screens | ${ghostCount} |`);
  if (snapshotFiles.length > 0) lines.push(`| Screenshots | ${snapshotFiles.length} |`);
  if (warnings.length > 0) lines.push(`| Validator warnings | ${warnings.length} |`);
  lines.push('');

  // ── Status distribution
  const byStatus = countBy(screens.map((s) => s.status));
  if (byStatus.size > 0) {
    lines.push('### Screen status');
    lines.push('');
    for (const [status, n] of byStatus) lines.push(`- **${status}** — ${n}`);
    lines.push('');
  }

  // ── TOC
  lines.push('## Contents');
  lines.push('');
  if (brief.exists) lines.push('1. [Brief](#brief)');
  if (sections.length > 0) lines.push('2. [Sections](#sections)');
  if (journeys.length > 0) lines.push('3. [Journeys](#journeys)');
  if (permissions.length > 0) lines.push('4. [Permissions](#permissions)');
  lines.push('5. [Screens](#screens)');
  if (fixtures.length > 0) lines.push('6. [Fixtures (data)](#fixtures-data)');
  if (snapshotFiles.length > 0) lines.push('7. [Screenshots](#screenshots)');
  if (sitemapEntries) lines.push('8. [Sitemap (intent vs reality)](#sitemap-intent-vs-reality)');
  if (warnings.length > 0) lines.push('9. [Validator warnings](#validator-warnings)');
  lines.push('');

  // ── Brief
  if (brief.exists) {
    lines.push('## Brief');
    lines.push('');
    lines.push('See [`brief.md`](./brief.md) for the complete project brief.');
    lines.push('');
    for (const f of brief.files) {
      lines.push(`### ${f.name}`);
      lines.push('');
      lines.push(f.content.trim());
      lines.push('');
    }
  }

  // ── Sections
  if (sections.length > 0) {
    lines.push('## Sections');
    lines.push('');
    for (const s of sections) {
      lines.push(`### ${s.label} \`${s.id}\``);
      if (s.description) lines.push(`> ${s.description}`);
      lines.push('');
      for (const sid of s.screenIds) {
        const screen = screens.find((x) => x.id === sid);
        lines.push(`- ${screen ? `**${screen.title}** — \`${screen.route}\`` : `_missing screen \`${sid}\`_`}`);
      }
      lines.push('');
    }
  }

  // ── Journeys
  if (journeys.length > 0) {
    lines.push('## Journeys');
    lines.push('');
    for (const j of journeys) {
      lines.push(`### ${j.title} \`${j.id}\``);
      if (j.description) lines.push(`> ${j.description}`);
      lines.push('');
      j.steps.forEach((sid, i) => {
        const screen = screens.find((x) => x.id === sid);
        lines.push(`${i + 1}. ${screen ? `**${screen.title}** \`${screen.route}\`` : `_missing \`${sid}\`_`}`);
      });
      lines.push('');
    }
  }

  // ── Permissions
  if (permissions.length > 0) {
    lines.push('## Permissions');
    lines.push('');
    lines.push('| id | label | default | modes | default mode |');
    lines.push('|---|---|---|---|---|');
    for (const p of permissions) {
      lines.push(
        `| \`${p.id}\` | ${p.label} | ${p.default ? '✅' : '—'} | ${p.modes.join(', ')} | \`${p.defaultMode}\` |`,
      );
    }
    lines.push('');
    lines.push('Each permission is consumed via `usePermission(id)` inside a screen. Authors decide hide-vs-disable-vs-message per call site.');
    lines.push('');
  }

  // ── Screens
  lines.push('## Screens');
  lines.push('');
  for (const s of screens) {
    lines.push(`### ${s.title} \`${s.id}\``);
    lines.push('');
    lines.push(`- **Route:** \`${s.route}\``);
    lines.push(`- **Status:** ${s.status} · v${s.version}`);
    lines.push(`- **Pattern:** ${s.layoutFamily} · ${s.viewport}`);
    if (s.journeys.length > 0)
      lines.push(`- **Journeys:** ${s.journeys.map((j) => `\`${j}\``).join(', ')}`);
    if (s.permissions && s.permissions.length > 0)
      lines.push(`- **Permissions:** ${s.permissions.map((p) => `\`${p}\``).join(', ')}`);
    if (s.fixtures.length > 0)
      lines.push(`- **Fixtures:** ${s.fixtures.map((f) => `\`${f}\``).join(', ')}`);
    if (s.relatedScreens.length > 0)
      lines.push(`- **Related:** ${s.relatedScreens.map((r) => `\`${r}\``).join(', ')}`);
    lines.push('');
    if (s.description) {
      lines.push(s.description);
      lines.push('');
    }
    if (s.states.length > 0) {
      lines.push('**States:**');
      for (const st of s.states) {
        lines.push(`- \`${st.id}\` — ${st.label}${st.description ? ` (${st.description})` : ''}`);
      }
      lines.push('');
    }
    if (s.knownGaps.length > 0) {
      lines.push('**Known gaps:**');
      for (const g of s.knownGaps) {
        lines.push(`- **${g.severity}** — ${g.description}`);
      }
      lines.push('');
    }
    // Inline screenshot if we have one named after the screen id.
    const shot = snapshotFiles.find((f) => f === `${s.id}.png`);
    if (shot) {
      lines.push(`![${s.title}](./snapshots/${shot})`);
      lines.push('');
    }
  }

  // ── Fixtures
  if (fixtures.length > 0) {
    lines.push('## Fixtures (data)');
    lines.push('');
    lines.push(
      'Sample data the screens render against. JSON payloads are bundled under [`./data/`](./data/) so engineering inherits the same shapes the mockups were designed against.',
    );
    lines.push('');
    for (const f of fixtures) {
      lines.push(`- \`${f.id}\`${f.description ? ` — ${f.description}` : ''}`);
    }
    lines.push('');
  }

  // ── Screenshots gallery
  if (snapshotFiles.length > 0) {
    lines.push('## Screenshots');
    lines.push('');
    for (const file of snapshotFiles) {
      lines.push(`### \`${file.replace(/\.png$/, '')}\``);
      lines.push('');
      lines.push(`![${file}](./snapshots/${file})`);
      lines.push('');
    }
  }

  // ── Sitemap
  if (sitemapEntries) {
    lines.push('## Sitemap (intent vs reality)');
    lines.push('');
    lines.push('| route | title | status |');
    lines.push('|---|---|---|');
    for (const e of sitemapEntries.entries) {
      const status = e.kind === 'real' ? '✅ implemented' : `✨ proposed${e.rationale ? ` — ${e.rationale}` : ''}`;
      lines.push(`| \`${e.route}\` | ${e.title} | ${status} |`);
    }
    lines.push('');
  }

  // ── Warnings
  if (warnings.length > 0) {
    lines.push('## Validator warnings');
    lines.push('');
    for (const w of warnings) {
      lines.push(`- \`${w.code}\`${w.subject ? ` (${w.subject})` : ''} — ${w.message}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`<sub>Generated by Mockup OS · \`build-handoff.ts\` · ${stamp}</sub>`);
  lines.push('');

  writeFileSync(ctx.outDir + '/README.md', lines.join('\n'), 'utf8');
}

function countBy(values: string[]): Map<string, number> {
  const m = new Map<string, number>();
  for (const v of values) m.set(v, (m.get(v) ?? 0) + 1);
  return m;
}

// ─── entry ──────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const all = await discoverProjects();
  const projects = args.project ? all.filter((p) => p.meta.id === args.project) : all;

  if (projects.length === 0) {
    if (args.project) {
      console.error(`No project with id "${args.project}" under /Projects/.`);
    } else {
      console.error('No projects discovered under /Projects/.');
    }
    process.exit(1);
  }

  for (const project of projects) {
    buildProject(project, args);
  }
}

// Only run main() when invoked directly (e.g. via `npm run handoff`).
// Importing this module from the sidecar must NOT trigger a build.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
